# Permalinks
#

permalink:           pretty
#Removed relative permalinks since it is no longer supported by Jekyll

# Setup
title:               Hannah Ling
tagline:             'Thoughts and writings from Pittsburgh'
description:         'Titus 2:11-14'
url:                 http://hannahling0.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hannah Ling
  url:               
  email:             hannahling@berkeley.edu
# Custom vars
version:             1.0.0
